apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z7zb237ph-nodejs 
  janus-idp.io/tekton: z7zb237ph-nodejs
  backstage.io/kubernetes-id: z7zb237ph-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z7zb237ph-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml