apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: z7zb237ph-nodejs-gitops
  description: This is GitOps manifest for z7zb237ph-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=z7zb237ph-nodejs
    backstage.io/kubernetes-id: z7zb237ph-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: z7zb237ph-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:z7zb237ph-nodejs
